In [21]:
import numpy as np

In [50]:
arr = np.array([1,2,3,4,5])
sum = arr.sum()
sum
multiDimArray= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(multiDimArray,'\n')
multiDimArray.shape
print(multiDimArray[1,:2],"\n")
print(multiDimArray.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[4 5] 

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [9]:
students


{'name': 'ravi', 'partner': 'foram'}

In [19]:
nums = [1,2,3,4,5]
increasedByOne = [x+1 for x in nums]
print(increasedByOne)

odds = [x for x in nums if x%2==0]
print("odds ",odds)

[2, 3, 4, 5, 6]
odds  [2, 4]
